type = "about"
title = "About"

[profile]
research_interests = [
  "Causal Inference and Decision Science",
  "Business Technology",
  "Combinatorial Optimization",
  "Bayesian Methods"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "A bit about me"

[[sections]]
id = "news"
type = "list"
title = "Lately"
source = "news.toml"
limit = 3
