type = "text"
title = "Applying for Predoctoral Positions in Social Sciences and Business"
description = "A brief review of my predoc applications during AY 2024–2025"
source = "blog/predoc.md"
toc = "nested"
