type = "text"
title = "Comparative Judgment, Pairwise Comparison, and Bradley–Terry Model"
description = "Using pairwise comparison data to assess abilities"
date = "2023-12-12"
tags = ["Statistics", "ML"]
source = "blog/cj.md"
toc = "none"
