type = "news"
title = "News"
description = "Updates, milestones, and announcements."

[[news]]
date = "2025-06-07"
content = "I graduated from The University of Chicago."

[[news]]
date = "2025-03-01"
content = "I will join Northwestern Kellogg as an Empirical Research Fellow."

[[news]]
date = "2024-07-01"
content = "I graduated from college."

[[news]]
date = "2024-05-15"
content = "I am entering The University of Chicago MAPSS (Economics concentration) this fall."

[[news]]
date = "2024-01-01"
content = "Happy New Year!"

[[news]]
date = "2023-11-07"
content = "I presented summer research on comparative judgment reliability at the University of Birmingham."
