type = "news"
title = "News"
description = "Updates, milestones, and announcements."

[[news]]
date = "2025-03-01"
content = "I will join Northwestern Kellogg as an Empirical Research Fellow this summer!"

[[news]]
date = "2023-11-07"
content = "I presented summer research on comparative judgment reliability at The University of Birmingham."
