name: Build and deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # <-- add this:
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
      - name: Install dependencies
        run: |
          gem uninstall bundler --all --executables --force --version '< 2'
          gem install bundler:2.6.9
          bundle _2.6.9_ install
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site
      - uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - uses: actions/deploy-pages@v4
